### ISSUE TITLE
Updating to newest version?

### ISSUE THREAD

**Issue by ghost** [cmatsuoka/mpg123-snap#1]
Was just wondering if I could open a request to update mpg123 to it's most current version 1.27.2  https://www.mpg123.de/download/mpg123-1.27.2.tar.bz2

**Comment by ghost** [comment]
Hey @cmatsuoka I appreciate your recent update to the mpg123 snap, it looks like version 1.28.0 is having some issues / had some updates to version 1.28.2. Any chance we could get an update to that? Thanks again for the work on this project. Best g00b

**Comment by cmatsuoka** [comment]
Hi, thanks for the heads up. I'll update it right now.

**Comment by ghost** [comment]
@cmatsuoka https://www.mpg123.de/#2021-10-17 whenever you're able to :bow:  (thank you again!)

**Comment by cmatsuoka** [comment]
Done!
